### ISSUE TITLE
author_label

### ISSUE THREAD

**Issue by yhchong** [PeterGriffinJin/Heterformer#2]
Hi,
How are the labels of the author for textless classification determined? 
Based on author_classification.py:170, there is supposed to be an 'author_label.npy' file but I am unable to find the preprocessing/code for reponsible saving that. Similar with classification.py:180. 
Could you please point me to the appropriate file for this? 

Thanks!

**Comment by PeterGriffinJin** [comment]
Hi there,

I'm so sorry for the late reply.

You can find the code on how we generate data for downstream classification tasks (both text-rich node classification and textless node classification) here: 

https://github.com/PeterGriffinJin/Heterformer/blob/main/data/book/generate_classification_data.ipynb

Please feel free to let me know if you have any other questions.

Best,
Bowen
