### ISSUE TITLE
Regarding paper labels in DBLP dataset

### ISSUE THREAD

**Issue by harshvardhan000** [PeterGriffinJin/Heterformer#3]
Hi, 

I downloaded the raw dataset of DBLP and trying to identify the paper labels. I am unable to identify the right attribute used to identify the paper label. I am attaching a screenshot of a sample json from the raw data.
<img width="1235" alt="Screenshot 2023-12-24 at 2 00 36 PM" src="https://github.com/PeterGriffinJin/Heterformer/assets/10085013/2c86bba0-ea99-4466-af0c-27f014edbeae">

regards
Harshvardhan.

**Comment by PeterGriffinJin** [comment]
Hi Harshvardhan,

Thank you so much for asking this question.

The right attribute which is used to identify the paper label in DBLP is "fos", which is "field of study" for short.

The code for how we generate data for node classification on DBLP can be found here:

https://github.com/PeterGriffinJin/Heterformer/blob/main/data/dblp/generate_classification_data.ipynb

Please feel free to let me know if you have any other questions.

Best,
Bowen

**Comment by harshvardhan000** [comment]
Thanks for the response, can I know how did you get the weights associated with different subjects in fos?
