### ISSUE TITLE
Twitter dataset format

### ISSUE THREAD

**Issue by callumhedemann** [PeterGriffinJin/Heterformer#4]
Hi there, I am trying to run your code using the twitter dataset but the files you provide are .txt files and your notebook is written to handle processed .json files. Is there code somewhere to process the .txt files to .json? Thanks

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you so much for your message and I'm sorry for my late reply.

You can find the JSON format file here: https://drive.google.com/drive/folders/1JZscw_9L_6ID9td9-c79QnwMsLCsD5Nh?usp=sharing.

Best,
Bowen
